name: Jira Auto Hold Daily

on:
  schedule:
    - cron: "0 13 * * *"   # 20:00 WIB
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Auto Hold Script
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          chmod +x scripts/*.sh
          ./scripts/auto_hold.sh
