name: Jira Auto Hold Daily

on:
  schedule:
    # Cron: 23:15 WIB = 16:15 UTC
    - cron: "10 18 * * *"
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show current time (for logging)
        run: |
          echo "Current UTC: $(date -u)"
          echo "Current WIB: $(TZ='Asia/Jakarta' date)"

      - name: Run Auto Hold Script
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          chmod +x scripts/*.sh
          ./scripts/auto_hold.sh
